import { AuditContext, CategoryResult, Finding } from "../types.js";
import { analyzeMarkdown, hasEmptySections } from "../detectors/markdown.js";
import { computeCategoryScore } from "../scoring/score.js";

const WEIGHT = 5;

// Generic descriptions that could apply to any project
const VAGUE_PHRASES = [
  "a modern web application",
  "a powerful tool",
  "a simple and elegant",
  "an easy-to-use",
  "built with the latest",
  "leverages cutting-edge",
  "seamlessly integrates",
  "state-of-the-art",
  "intuitive and user-friendly",
  "robust and scalable",
  "revolutionize your workflow",
  "take your productivity",
  "next-generation",
  "blazing fast",
  "fully customizable solution",
];

export function runAiRedFlagsAudit(ctx: AuditContext): CategoryResult {
  const findings: Finding[] = [];
  const passed: string[] = [];

  const content = ctx.readmeContent ?? "";
  const lowerContent = content.toLowerCase();

  // --- TODO or FIXME in README ---
  const todoCount = (content.match(/\bTODO\b/g) ?? []).length;
  const fixmeCount = (content.match(/\bFIXME\b/g) ?? []).length;
  if (todoCount > 0 || fixmeCount > 0) {
    findings.push({
      category: "AI Red Flags",
      severity: "high",
      title: `README contains ${todoCount + fixmeCount} TODO/FIXME item(s)`,
      explanation: "TODO/FIXME comments in your README signal an unfinished, unreviewed document — a classic sign of an AI-generated draft.",
      recommendation: "Complete or remove all TODO and FIXME items before launching.",
      file: "README.md",
    });
  } else {
    passed.push("No TODO/FIXME in README");
  }

  // --- Lorem ipsum ---
  if (/lorem ipsum/i.test(content)) {
    findings.push({
      category: "AI Red Flags",
      severity: "critical",
      title: "Lorem ipsum placeholder text found in README",
      explanation: "Lorem ipsum is a placeholder text generated by AI or template tools. It means the README was never properly filled in.",
      recommendation: "Replace all Lorem ipsum placeholder text with real content.",
      file: "README.md",
    });
  } else {
    passed.push("No Lorem ipsum placeholder text");
  }

  // --- "coming soon" more than 2 times ---
  const comingSoonCount = (lowerContent.match(/coming soon/g) ?? []).length;
  if (comingSoonCount > 2) {
    findings.push({
      category: "AI Red Flags",
      severity: "medium",
      title: `"Coming soon" appears ${comingSoonCount} times`,
      explanation: 'Overuse of "coming soon" signals that key features are not yet built.',
      recommendation: 'Remove "coming soon" placeholders. Only mention planned features in a dedicated Roadmap section.',
      file: "README.md",
    });
  } else if (comingSoonCount > 0) {
    passed.push(`"Coming soon" appears ${comingSoonCount} time(s) — acceptable`);
  } else {
    passed.push('No excessive "coming soon" usage');
  }

  // --- "placeholder" text ---
  const placeholderCount = (lowerContent.match(/\bplaceholder\b/g) ?? []).length;
  if (placeholderCount > 0) {
    findings.push({
      category: "AI Red Flags",
      severity: "high",
      title: `README contains the word "placeholder" ${placeholderCount} time(s)`,
      explanation: 'The word "placeholder" in a README indicates unfilled template sections.',
      recommendation: 'Replace all placeholder references with real content.',
      file: "README.md",
    });
  } else {
    passed.push('No "placeholder" text in README');
  }

  // --- Fake or broken badges ---
  const md = analyzeMarkdown(content);
  // Only flag badges whose URLs are specifically CI-related, not generic badges like
  // npm version or license. Patterns: GitHub Actions URL, Travis/Circle/Codecov badge URLs,
  // or shields.io GitHub workflow badge.
  const hasCiBadgeInReadme =
    /github\.com\/[^/\s"')]+\/[^/\s"')]+\/actions/.test(content) ||
    /travis-ci\.(?:org|com)\/badge/i.test(content) ||
    /circleci\.com\/gh\//i.test(content) ||
    /img\.shields\.io\/github\/actions\/workflow/i.test(content) ||
    /img\.shields\.io\/(?:travis|circleci|appveyor|jenkins)/i.test(content);

  const hasWorkflows = ctx.files.some((f) => f.startsWith(".github/workflows/"));

  if (hasCiBadgeInReadme && !hasWorkflows) {
    findings.push({
      category: "AI Red Flags",
      severity: "high",
      title: "CI status badge present but no GitHub Actions workflow found",
      explanation: "You have a CI badge in your README but no .github/workflows/ directory. The badge will show as failing or broken.",
      recommendation: "Remove the CI badge or set up GitHub Actions to make it accurate.",
      file: "README.md",
    });
  } else if (md.badgeCount > 0) {
    passed.push(`Has ${md.badgeCount} badge(s)`);
  }

  // --- Inconsistent project name ---
  if (ctx.packageJson && md.h1Text) {
    const pkgName = ctx.packageJson["name"];
    if (typeof pkgName === "string" && pkgName.length > 0) {
      const normalizedH1 = md.h1Text.toLowerCase().replace(/[-_\s]/g, "");
      const normalizedPkg = pkgName.replace(/^@[^/]+\//, "").toLowerCase().replace(/[-_\s]/g, "");
      const match =
        normalizedH1.includes(normalizedPkg) ||
        normalizedPkg.includes(normalizedH1) ||
        normalizedH1 === normalizedPkg;
      if (!match && normalizedH1.length > 0 && normalizedPkg.length > 0) {
        findings.push({
          category: "AI Red Flags",
          severity: "medium",
          title: "README title doesn't match package.json name",
          explanation: `README H1 is "${md.h1Text}" but package.json name is "${pkgName}". This inconsistency signals a hastily assembled project.`,
          recommendation: "Ensure the README title matches the package name.",
          file: "README.md",
        });
      } else {
        passed.push("README title matches package name");
      }
    }
  }

  // --- Empty sections ---
  if (content.length > 0 && hasEmptySections(content)) {
    findings.push({
      category: "AI Red Flags",
      severity: "medium",
      title: "README has empty sections",
      explanation: "One or more section headings are immediately followed by another heading with no content in between. This is a sign of an AI-generated scaffold that was never filled in.",
      recommendation: "Remove empty sections or fill them with real content.",
      file: "README.md",
    });
  } else if (content.length > 0) {
    passed.push("No empty sections in README");
  }

  // --- Vague generic description ---
  const vagueCount = VAGUE_PHRASES.filter((phrase) =>
    lowerContent.includes(phrase.toLowerCase())
  ).length;
  if (vagueCount >= 2) {
    findings.push({
      category: "AI Red Flags",
      severity: "medium",
      title: "README uses multiple vague/generic phrases",
      explanation: `Found ${vagueCount} generic phrases that could apply to any project. This signals AI-generated boilerplate.`,
      recommendation: "Replace generic marketing language with specific, concrete descriptions of what your project actually does.",
      file: "README.md",
    });
  } else {
    passed.push("README uses specific language");
  }

  // --- "built with AI" without real docs ---
  const mentionsAiBuild =
    /built with (ai|chatgpt|gpt|claude|copilot)/i.test(content) ||
    /generated (by|with|using) (ai|chatgpt|gpt|claude|copilot)/i.test(content);
  const hasUsageDocs =
    ctx.readmeContent !== null &&
    ctx.readmeContent.length > 1000 &&
    md.codeBlocks.length >= 2;

  if (mentionsAiBuild && !hasUsageDocs) {
    findings.push({
      category: "AI Red Flags",
      severity: "low",
      title: 'Project mentions being "built with AI" but lacks usage documentation',
      explanation: "Mentioning AI involvement without thorough documentation raises credibility concerns.",
      recommendation: "Add comprehensive usage documentation, examples, and code blocks to demonstrate the project works.",
      file: "README.md",
    });
  }

  // --- Repeated "This project" phrases (AI filler) ---
  const thisProjectCount = (content.match(/this project/gi) ?? []).length;
  if (thisProjectCount > 4) {
    findings.push({
      category: "AI Red Flags",
      severity: "low",
      title: `"This project" used ${thisProjectCount} times`,
      explanation: 'Overusing "This project" is a common AI writing pattern.',
      recommendation: "Vary your language. Use the project name or more specific terminology.",
      file: "README.md",
    });
  } else {
    passed.push("Language variety looks good");
  }

  return {
    category: "AI Red Flags",
    score: computeCategoryScore(findings),
    weight: WEIGHT,
    findings,
    passed,
  };
}
