import { AuditReport, CategoryResult, Finding, Severity } from "../types.js";

function severityEmoji(severity: Severity): string {
  switch (severity) {
    case "critical": return "🔴";
    case "high": return "🟠";
    case "medium": return "🟡";
    case "low": return "🔵";
    case "info": return "⚪";
  }
}

function scoreEmoji(score: number): string {
  if (score >= 80) return "✅";
  if (score >= 60) return "⚠️";
  return "❌";
}

function launchStatus(report: AuditReport): string {
  if (report.launchReady) return "✅ **LAUNCH READY**";
  if (report.overallScore >= 60) return "⚠️ **NEEDS WORK**";
  return "❌ **NOT READY**";
}

export function renderMarkdownReport(report: AuditReport): string {
  const lines: string[] = [];

  lines.push("# OpenLaunchKit Audit Report");
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Project** | ${report.projectName} |`);
  lines.push(`| **Audited** | ${report.auditedAt} |`);
  lines.push(`| **Path** | \`${report.projectPath}\` |`);
  lines.push(`| **Overall Score** | ${report.overallScore}/100 |`);
  lines.push(`| **Status** | ${launchStatus(report)} |`);
  lines.push("");

  // Category summary table
  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score | Status |");
  lines.push("|----------|-------|--------|");
  for (const cat of report.categories) {
    lines.push(
      `| ${cat.category} | ${cat.score}/100 | ${scoreEmoji(cat.score)} |`
    );
  }
  lines.push("");

  // Top fixes
  if (report.topFixes.length > 0) {
    lines.push("## Top Fixes");
    lines.push("");
    report.topFixes.forEach((fix, idx) => {
      lines.push(
        `### ${idx + 1}. ${severityEmoji(fix.severity)} [${fix.severity.toUpperCase()}] ${fix.title}`
      );
      if (fix.file) {
        lines.push(`**File:** \`${fix.file}\``);
        lines.push("");
      }
      lines.push(`**Explanation:** ${fix.explanation}`);
      lines.push("");
      lines.push(`**Recommendation:** ${fix.recommendation}`);
      lines.push("");
    });
  }

  // Detailed category results
  lines.push("## Detailed Results");
  lines.push("");

  for (const cat of report.categories) {
    lines.push(`### ${scoreEmoji(cat.score)} ${cat.category} — ${cat.score}/100`);
    lines.push("");

    if (cat.passed.length > 0) {
      lines.push("**Passing checks:**");
      for (const p of cat.passed) {
        lines.push(`- ✅ ${p}`);
      }
      lines.push("");
    }

    if (cat.findings.length > 0) {
      lines.push("**Issues found:**");
      lines.push("");
      for (const finding of cat.findings) {
        lines.push(`#### ${severityEmoji(finding.severity)} [${finding.severity.toUpperCase()}] ${finding.title}`);
        if (finding.file) {
          lines.push(`> File: \`${finding.file}\``);
          lines.push("");
        }
        lines.push(finding.explanation);
        lines.push("");
        lines.push(`**Fix:** ${finding.recommendation}`);
        lines.push("");
      }
    } else {
      lines.push("_No issues found in this category._");
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push("_Generated by [OpenLaunchKit](https://github.com/stephenywilson/openlaunchkit)_");
  lines.push("");

  return lines.join("\n");
}
